MERGE INTO PROD_BRONCE_CARS_PROPERTIES.CP_STG.D_CARS AS T
USING (
  SELECT *
  FROM (
    SELECT
      d.*,
      ROW_NUMBER() OVER (
        PARTITION BY d.MATRICULA
        ORDER BY COALESCE(d.T_REC_UPD_TST, d.T_REC_INS_TST, TO_TIMESTAMP_NTZ(0)) DESC
      ) AS rn
    FROM DEV_BRONCE_CARS_PROPERTIES.CP_STG.D_CARS d
  )
  WHERE rn = 1
) AS S
ON T.MATRICULA = S.MATRICULA
WHEN MATCHED
  AND COALESCE(T.T_REC_UPD_TST, T.T_REC_INS_TST, TO_TIMESTAMP_NTZ(0))
      < COALESCE(S.T_REC_UPD_TST, S.T_REC_INS_TST, TO_TIMESTAMP_NTZ(0))
THEN UPDATE SET
  T.DNI_PROPIETARIO   = S.DNI_PROPIETARIO,
  T.MARCA_VEHICULO    = S.MARCA_VEHICULO,
  T.PROVINCIA         = S.PROVINCIA,
  T.MUNICIPIO         = S.MUNICIPIO,
  T.FECHA_PROPIETARIO = S.FECHA_PROPIETARIO,
  T.T_REC_INS_TST     = S.T_REC_INS_TST,
  T.T_REC_UPD_TST     = S.T_REC_UPD_TST
WHEN NOT MATCHED THEN
  INSERT (
    MATRICULA, DNI_PROPIETARIO, MARCA_VEHICULO, PROVINCIA, MUNICIPIO,
    FECHA_PROPIETARIO, T_REC_INS_TST, T_REC_UPD_TST
  )
  VALUES (
    S.MATRICULA, S.DNI_PROPIETARIO, S.MARCA_VEHICULO, S.PROVINCIA, S.MUNICIPIO,
    S.FECHA_PROPIETARIO, S.T_REC_INS_TST, S.T_REC_UPD_TST
  );
