CREATE OR REPLACE DATABASE CICD_CONTROL;
CREATE OR REPLACE SCHEMA CICD_CONTROL.DEPLOYMENTS;

CREATE OR REPLACE TABLE CICD_CONTROL.DEPLOYMENTS.DEPLOY_LOG (
    ENVIRONMENT VARCHAR,
    VERSION VARCHAR,
    EXECUTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR,
    EXECUTED_BY VARCHAR
);


--------------------


CREATE USER IF NOT EXISTS GH_CICD
  PASSWORD = 'PASS' 
  DEFAULT_ROLE = SYSADMIN
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Usuario usado por GitHub Actions para despliegues automáticos';


CREATE ROLE IF NOT EXISTS DEV_ROLE;
CREATE ROLE IF NOT EXISTS SIT_ROLE;
CREATE ROLE IF NOT EXISTS PROD_ROLE;


GRANT ROLE DEV_ROLE TO USER GH_CICD;
GRANT ROLE SIT_ROLE TO USER GH_CICD;
GRANT ROLE PROD_ROLE TO USER GH_CICD;


CREATE WAREHOUSE IF NOT EXISTS DEV_WH  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE WAREHOUSE IF NOT EXISTS SIT_WH  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE WAREHOUSE IF NOT EXISTS PROD_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;


GRANT USAGE ON WAREHOUSE DEV_WH  TO ROLE DEV_ROLE;
GRANT USAGE ON WAREHOUSE SIT_WH  TO ROLE SIT_ROLE;
GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE PROD_ROLE;


CREATE DATABASE IF NOT EXISTS CICD_CONTROL;
CREATE SCHEMA IF NOT EXISTS CICD_CONTROL.DEPLOYMENTS;

CREATE OR REPLACE TABLE CICD_CONTROL.DEPLOYMENTS.DEPLOY_LOG (
    ENVIRONMENT VARCHAR,
    VERSION VARCHAR,
    EXECUTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR,
    EXECUTED_BY VARCHAR
);


GRANT USAGE, CREATE TABLE
  ON SCHEMA CICD_CONTROL.DEPLOYMENTS TO ROLE DEV_ROLE;
GRANT USAGE, CREATE TABLE
  ON SCHEMA CICD_CONTROL.DEPLOYMENTS TO ROLE SIT_ROLE;
GRANT USAGE, CREATE TABLE
  ON SCHEMA CICD_CONTROL.DEPLOYMENTS TO ROLE PROD_ROLE;


  GRANT ROLE PROD_ROLE TO USER manolito;


GRANT CREATE USER       ON ACCOUNT TO ROLE DEV_ROLE;
GRANT CREATE ROLE       ON ACCOUNT TO ROLE DEV_ROLE;
GRANT CREATE DATABASE   ON ACCOUNT TO ROLE DEV_ROLE;
GRANT CREATE WAREHOUSE  ON ACCOUNT TO ROLE DEV_ROLE;
GRANT MANAGE GRANTS     ON ACCOUNT TO ROLE DEV_ROLE;  
GRANT MONITOR           ON ACCOUNT TO ROLE DEV_ROLE;


GRANT CREATE USER       ON ACCOUNT TO ROLE SIT_ROLE;
GRANT CREATE ROLE       ON ACCOUNT TO ROLE SIT_ROLE;
GRANT CREATE DATABASE   ON ACCOUNT TO ROLE SIT_ROLE;
GRANT CREATE WAREHOUSE  ON ACCOUNT TO ROLE SIT_ROLE;
GRANT MANAGE GRANTS     ON ACCOUNT TO ROLE SIT_ROLE;
GRANT MONITOR           ON ACCOUNT TO ROLE SIT_ROLE;


GRANT CREATE USER       ON ACCOUNT TO ROLE PROD_ROLE;
GRANT CREATE ROLE       ON ACCOUNT TO ROLE PROD_ROLE;
GRANT CREATE DATABASE   ON ACCOUNT TO ROLE PROD_ROLE;
GRANT CREATE WAREHOUSE  ON ACCOUNT TO ROLE PROD_ROLE;
GRANT MANAGE GRANTS     ON ACCOUNT TO ROLE PROD_ROLE;
GRANT MONITOR           ON ACCOUNT TO ROLE PROD_ROLE;
