create or replace TABLE DEV_BRONCE_CARS_PROPERTIES.CP_STG.T_METADATA (
	ID NUMBER(38,0),
	INGESTION_NAME VARCHAR(16777216),
	ACTIVE BOOLEAN,
	SOURCE VARIANT,
	SOURCE_TYPE VARCHAR(16777216),
	TARGET VARIANT,
	TARGET_TYPE VARCHAR(16777216),
	MERGE_KEYS ARRAY,
	DEDUPE_ORDER ARRAY,
	UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);


