CREATE USER DEV_CDR PASSWORD='DEV_CDR' ;
--Role for CDR user in DEV
CREATE ROLE DEV_CDR;

--Grant role to user
GRANT ROLE DEV_CDR TO USER DEV_CDR;


-- Create databases

CREATE DATABASE DEV_BRONCE_CARS_PROPERTIES;
CREATE SCHEMA DEV_BRONCE_CARS_PROPERTIES.CP_STG;
CREATE TABLE DEV_BRONCE_CARS_PROPERTIES.CP_STG.D_CARS
(
matricula VARCHAR(50),
dni_propietario VARCHAR(50),
marca_vehiculo VARCHAR(99),
provincia VARCHAR(50),
municipio VARCHAR(50),
fecha_propietario VARCHAR(50),
T_REC_INS_TST TIMESTAMP,
T_REC_UPD_TST TIMESTAMP
);

GRANT USAGE ON DATABASE DEV_BRONCE_CARS_PROPERTIES TO ROLE DEV_CDR;
GRANT USAGE ON SCHEMA DEV_BRONCE_CARS_PROPERTIES.CP_STG TO ROLE DEV_CDR;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE DEV_BRONCE_CARS_PROPERTIES.CP_STG.D_CARS TO ROLE DEV_CDR;
-- Database para ciudadanos
CREATE DATABASE DEV_BRONCE_REGISTRO_CIUDADANO;
CREATE SCHEMA DEV_BRONCE_REGISTRO_CIUDADANO.RC_STG;
CREATE TABLE DEV_BRONCE_REGISTRO_CIUDADANO.RC_STG.D_CIUDADANOS
(
dni VARCHAR(50),
nombre_completo VARCHAR(99),
ccaa VARCHAR(50),
provincia VARCHAR(50),
muncipio VARCHAR(50),
T_REC_INS_TST TIMESTAMP,
T_REC_UPD_TST TIMESTAMP
);

GRANT USAGE ON DATABASE DEV_BRONCE_REGISTRO_CIUDADANO TO ROLE DEV_CDR;
GRANT USAGE ON SCHEMA DEV_BRONCE_REGISTRO_CIUDADANO.RC_STG TO ROLE DEV_CDR;
GRANT INSERT, SELECT, UPDATE ON TABLE DEV_BRONCE_REGISTRO_CIUDADANO.RC_STG.D_CIUDADANOS TO ROLE DEV_CDR;

-- Database para Ayuntamiento Alhaurin

CREATE DATABASE DEV_BRONCE_ALAHURIN_GRANDE_VEHICULOS;
CREATE SCHEMA DEV_BRONCE_ALAHURIN_GRANDE_VEHICULOS.AGV_STG;
CREATE TABLE DEV_BRONCE_ALAHURIN_GRANDE_VEHICULOS.AGV_STG.D_CARS(
matricula VARCHAR(50),
dni_propietario VARCHAR(50),
marca_vehiculo VARCHAR(99),
provincia VARCHAR(50),
fecha_propietario VARCHAR(50),
T_REC_INS_TST TIMESTAMP,
T_REC_UPD_TST TIMESTAMP
);
-- Database para Málaga
CREATE DATABASE DEV_BRONCE_MALAGA_VEHICULOS;
CREATE SCHEMA DEV_BRONCE_MALAGA_VEHICULOS.MV_STG;
CREATE TABLE DEV_BRONCE_MALAGA_VEHICULOS.MV_STG.D_CARS(
matricula VARCHAR(50),
dni_propietario VARCHAR(50),
marca_vehiculo VARCHAR(99),
provincia VARCHAR(50),
fecha_propietario VARCHAR(50),
T_REC_INS_TST TIMESTAMP,
T_REC_UPD_TST TIMESTAMP
);


GRANT USAGE ON DATABASE DEV_BRONCE_ALAHURIN_GRANDE_VEHICULOS TO ROLE DEV_CDR;
GRANT USAGE ON SCHEMA DEV_BRONCE_ALAHURIN_GRANDE_VEHICULOS.AGV_STG TO ROLE DEV_CDR;
GRANT INSERT, SELECT, UPDATE ON TABLE DEV_BRONCE_ALAHURIN_GRANDE_VEHICULOS.AGV_STG.D_CARS TO ROLE DEV_CDR;


GRANT USAGE ON DATABASE DEV_BRONCE_MALAGA_VEHICULOS TO ROLE DEV_CDR;
GRANT USAGE ON SCHEMA DEV_BRONCE_MALAGA_VEHICULOS.MV_STG TO ROLE DEV_CDR;
GRANT INSERT, SELECT, UPDATE ON TABLE DEV_BRONCE_MALAGA_VEHICULOS.MV_STG.D_CARS TO ROLE DEV_CDR;
