name: (DEPRECATED) Deploy DEV (branch dev)
on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read
  id-token: write   # si usas OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true

      - name: Fetch latest repo in Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          snow sql -q "
            USE ROLE DEV_CDR;
            USE DATABASE DEV_BRONCE_CARS_PROPERTIES;
            USE SCHEMA CP_STG;
            ALTER GIT REPOSITORY GITHUB_REPO FETCH;
          "

      - name: Run SQL from branch dev
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          snow sql -q "
            USE ROLE DEV_CDR;
            USE WAREHOUSE DEV_WH;
            USE DATABASE DEV_BRONCE_CARS_PROPERTIES;
            USE SCHEMA CP_STG;
            EXECUTE IMMEDIATE FROM @GITHUB_REPO/branches/dev/sql/001_create_db_objects.sql;
            EXECUTE IMMEDIATE FROM @GITHUB_REPO/branches/dev/sql/002_alter_things.sql;
          "
