name: Deploy SIT (branch sit)
on:
  push:
    branches: [ "sit" ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: sit
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        with:
          use-oidc: true

      - name: Fetch latest repo in Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          snow sql -q "
            USE ROLE SIT_ROLE;
            USE DATABASE SIT_BRONCE_CARS_PROPERTIES;
            USE SCHEMA CP_STG;
            ALTER GIT REPOSITORY GITHUB_REPO FETCH;
          "

      - name: Run SQL from branch sit
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          snow sql -q "
            USE ROLE SIT_ROLE;
            USE WAREHOUSE SIT_WH;
            USE DATABASE SIT_BRONCE_CARS_PROPERTIES;
            USE SCHEMA CP_STG;
            EXECUTE IMMEDIATE FROM @GITHUB_REPO/branches/sit/sql/001_create_db_objects.sql;
            EXECUTE IMMEDIATE FROM @GITHUB_REPO/branches/sit/sql/002_alter_things.sql;
          "
